server:
  port: 8888


dubbo:
  application:
    name: boot-provider
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: registry
  provider:
    timeout: 60000

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/cloud?characterEncoding=utf8&useSSL=true
    username: root
    password: a123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    useSSL: false
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mail:
    host: smtp.qq.com
    username: 993874575@qq.com
    password: nvfrmoojeozqbdia
    default-encoding: UTF-8
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: a123
      #指定最小的消费者数量
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        # 指定Acknowledge的模式，我这里是手工确认的
        acknowledge-mode: manual
        # 指定一个请求能处理多少个消息，如果有事务的话，必须大于等于transaction数量
        prefetch: 1
      #指定最大的消费者数量
      #指定连接到broker的virtual host
    virtual-host: /